app = "player-tracker-gpu"

primary_region = "ord"  # If you change this, ensure it's to a region that offers GPUs
# vm.size = "a100-40gb"
# swap_size_mb = 32768    # This enables 32GB swap

[[vm]]
  size = "shared-cpu-2x"
  memory = "16gb"
  cpus = 4
  cpu_kind = "performance"
  gpus = 1
  gpu_kind = "a100-pcie-40gb"

[build]
  dockerfile = "Dockerfile"

[build.args]
  NONROOT_USER = "appuser"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"

  [[services.http_checks]]
    interval = "30s"
    timeout = "15s"
    grace_period = "180s"    # Critical for long model loading times
    method = "get"
    path = "/healthz"        # Adjust based on your app
    protocol = "http"
    restart_limit = 0


[[mounts]]
  source = "data"
  destination = "/home/appuser"
