_target_: tracker.algorithms.tracker.Tracker
batch_size: 1
tracker_type: 'strong_sort'
cfg:
  per_class: False
  min_conf: 0.1
  max_cos_dist: 0.2
  max_iou_dist: 0.7
  max_age: 100
  n_init: 3
  nn_budget: 100
  mc_lambda: 0.98
  ema_alpha: 0.9
  reid_weights: '${model_dir}/reid/feature_extractor_osnet_x1_0.onnx'
  half: true
