# Main config
device: cpu
video_buffer_size: 50
video_path: ""
target_fps: 15

defaults:
  - detector: yolo_api
  - reid: feature_extractor_tensorrt
  - tracker: bot_sort
  - gta_link: refiner
  - _self_

modules: # Allows module-specific batch_size and other configuration
  detector: {batch_size: 1}
  feature_extractor: {batch_size: 32}  # Reduced from 8 to avoid context conflicts
  tracker: {batch_size: 1}
  refiner: {batch_size: 100}

# Path definitions
home_dir: "${oc.env:HOME}"
data_dir: "${project_dir}/data"
model_dir: "${project_dir}/pretrained_models"

experiment_name: "player_tracking"
project_dir: "${hydra:runtime.cwd}"

save_results: true
overlay_video: true
save_to_aws: true
hydra:
  run:
    dir: "outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
    # dir: "outputs"