_target_: tracker.reid.feature_extractor_tensorrt.TensorRTFeatureExtractor
batch_size: 1  # Reduced from 8 to avoid CUDA context conflicts
cfg:
  model_name: 'osnet_x1_0_tensorrt'
  # TensorRT engine path - you'll need to convert your ONNX model to TensorRT engine
  model_path: '${model_dir}/reid/feature_extractor_osnet_x1_0_L4.engine'
  image_size: [256, 128]
  pixel_mean: [0.485, 0.456, 0.406]
  pixel_std: [0.229, 0.224, 0.225]
  pixel_norm: True
  device: 'cuda'
  verbose: True  # Enable verbose logging for debugging
  # TensorRT specific settings - conservative for stability
  optimal_batch_size: 1  # Conservative batch size
  enable_batch_padding: False  # Disable padding to reduce complexity
  max_workspace_size: 536870912  # 512MB workspace (reduced from 1GB)
  fp16_mode: False  # Disable FP16 for better compatibility
  int8_mode: False  # Keep INT8 disabled
  dynamic_shapes: False  # Disable dynamic shapes for better stability
